package com.example.playlistmaker

const val MY_SAVES = "my saves"
const val THEME = "theme"
const val LIST_TRACKS = "list tracks"
const val TRACK = "track"
const val ENTERED_TEXT = "ENTERED_TEXT"
const val RECYCLER_VISIBILITY = "RECYCLER_VISIBILITY"
const val IMAGE_ERROR_VISIBILITY = "IMAGE_ERROR_VISIBILITY"
const val IMAGE_ERROR_IMAGE_RESOURCE = "IMAGE_ERROR_IMAGE_RESOURCE"
const val TEXT_ERROR_VISIBILITY = "TEXT_ERROR_VISIBILITY"
const val TEXT_ERROR_RESOURCE = "TEXT_ERROR_RESOURCE"
const val BUTTON_UPDATE_VISIBILITY = "BUTTON_UPDATE_VISIBILITY"
const val MILLISECONDS_IN_SECOND = 1000L
const val SECONDS_IN_MINUTE = 60
const val TIME_FORMAT = "%02d:%02d"
const val CORNER_RADIUS_DP_LOGO_500 = 8f